export const CREATE_TICKET_START = "CREATE_TICKET_START";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_ERROR = "CREATE_TICKET_ERROR";
export const CLEAR_CREATE_TICKET_STORE = "CLEAR_CREATE_TICKET_STORE";

export const GET_TICKETS_START = "GET_TICKETS_START";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_ERROR = "GET_TICKETS_ERROR";
export const CLEAR_GET_TICKETS_STORE = "CLEAR_GET_TICKETS_STORE";
